TLS:
  keyPath: "./project/static/certificates/h-hnetdisk-com-iis-0901115710.key"
  pemPath: "./project/static/certificates/h-hnetdisk-com-iis-0901115710.pem"

Server:
  port: 443

Database:
  dbPath: "./project/static/database/nas.db"

DiskRoot: "/Users/hanminghao/Desktop/study/NAS_Disk_Root/"

keyIvYmlPath: "./project/static/aes.yml"

jwtKeyPath: "./project/static/jwtKey.yml"