TLS:
  keyPath: "./project/static/certificates/h-hnetdisk-com-iis-0901115710.key"
  pemPath: "./project/static/certificates/h-hnetdisk-com-iis-0901115710.pem"

Server:
  port: 443

Database:
  dbPath: "./project/static/database/nas.db"

DiskRoot: "/Users/hanminghao/Desktop/study/NAS_Disk_Root/"

Aes:
  keyIvYmlPath: "./project/static/aes.yml"

CheckDir:
  pageSize: 20

ChaCha20:
  keyNonceYmlPath: "./project/static/chacha20.yml"

jwtKeyPath: "./project/static/jwtKey.yml"